- package.json
- src/__configuration__/roadmap/index.tsx
- yarn.lock
Fixes an incorrect description for workflows on roadmap .
- Fix bad copy/paste
- Update to latest components (smaller bundle)
> Update incorrect descriptions on roadmap

- src/__configuration__/roadmap/index.tsx
- Mark Angular components in progress on roadmap
> Update roadmap with in-progress items

- src/docs/patterns/internationalization.mdx
- This seems a bit light; what other changes were expected?
- Updated the implementation section to include links to Angular Material, Material UI, i18next's solution library.
> Update implementation section

- src/docs/development/environment.mdx
- src/docs/get-started/mobile.mdx
-  Temporary ignore on 2 links for android studio
- markdown-link-check-disable and markdown-link-check-enable
-
> Ignore android studio links

- src/app/components/layout/Divider.tsx
Fixes an issue with content scrolling horizontally on smaller screens.
- Add max width to the divider components
> Fix overflow X

- src/__configuration__/navigationMenu/navigation.tsx
- src/app/components/patterns/ImageGrid.tsx
- src/docs/development/cli.mdx
- src/docs/development/environment.mdx
- src/docs/development/frameworks-mobile/cordova.mdx
- src/docs/development/frameworks-mobile/intro.mdx
- src/docs/development/frameworks-mobile/ionic.mdx
- src/docs/development/frameworks-mobile/react-native.mdx
- src/docs/development/frameworks-web/angular.mdx
- src/docs/development/frameworks-web/react.mdx
- src/docs/development/index.tsx
- src/docs/development/testing.mdx
- src/docs/style/typography.mdx
Fixes #143 
- Reorganize getting started guide contents
- Add information about the PX Blue CLI
- Add npm equivalents for yarn commands
- Fix error from prettier on the ImageGrid with two captions
> Reorganize getting started guides

- src/__configuration__/markdown/markdownMapping.tsx
- src/app/components/layout/PageContent.tsx
- src/app/components/patterns/DemoCard.tsx
- src/app/components/patterns/ImageGrid.tsx
- src/app/components/patterns/MaterialDesignDescription.tsx
- src/app/components/resources/ResourceRow.tsx
- src/app/shared/constants.ts
- src/docs/development/frameworks-web/angular.mdx
- src/docs/development/frameworks-web/react.mdx
- src/docs/patterns/lists.mdx
Fixes #152 fixes #169 .
- Change the global page padding to 24px
- Removed a few unused props from ResourceRow
> Clean up styles

- src/docs/patterns/internationalization.mdx
- Update angular i18n section to align with the updated example
> Wordsmithing of ng i18n section

- src/docs/development/frameworks-mobile/react-native.mdx
For PXBLUE-1376
- Update instructions to make react-native-paper the official supported library
> Update react native guide for RNP

- public/index.html
- Add a meta tag to index.html to make our site appear in a regular google search
- Shall be pushed to master branch to have this go through
> Add gcse verification meta tag

- public/index.html
- Add site verification meta tag
> Add google site verification

- public/404.html
Same with https://github.com/pxblue/doc-it/pull/181
> Update 404 routing

- public/404.html
> Revert "Update 404 routing"

- public/404.html
- src/index.tsx
> Revert "Hotfix/seo popstate"

- src/__types__/index.ts
- src/app/pages/Roadmap.tsx
- src/docs/development/frameworks-mobile/react-native.mdx
- Support roadmap tags for pre-release (purple) and deferred (orange)
> Add new tags for roadmap

- .circleci/config.yml
Remove cypress temporarily while waiting for the applitool ticket
> Remove cypress

- src/docs/patterns/overlay.mdx
For PXBLUE-1351
- Add in Kyle's new content
- Wordsmith a little
> Tweak the overlays pattern

- src/app/router/navigationDrawer.tsx
Fixes #166.
- Remove box-shadow from the drawer
> Remove box-shadow from the drawer

- .circleci/config.yml
- package.json
- src/docs/patterns/forms.mdx
- Add prettier check to circle ci
- 
-
> Use prettier

- src/docs/release-notes/R16/R16.mdx
- Change the order of some of the release notes to condense things a little
> Re-organize some release notes

- src/app/api/index.tsx
- src/app/pages/Roadmap.tsx
-  Update doc'it to point to R17 data
- 
-
> Update source road map bucket with R17

- src/app/pages/SearchBar.tsx
Fixes #216.
- Fixes the logic on the close button (when you haven't searched for anything)
> Fix search clear button

- src/__configuration__/markdown/markdownMapping.tsx
Fixes broken mailto link on the contactus page.
- Add mailto check in the mdx translator
> Fix the broken mailto link

- src/app/pages/Roadmap.tsx
For @huayunh 
- Don't filter by framework when design is selected
- Let the filter toolbar scroll horizontally on smaller screens
> Fix Roadmap Filtering Behaviors

- src/app/pages/Roadmap.tsx
- use marginBottom instead of lineHeight to adjust the leftComponent placement
Up: after
Down: before
> Fix alignment of leftComponent

- src/docs/patterns/appbar.mdx
- src/docs/patterns/empty-states.mdx
- src/docs/patterns/forms.mdx
- src/docs/patterns/internationalization.mdx
- src/docs/patterns/lists.mdx
- src/docs/patterns/login.mdx
- src/docs/patterns/navigation.mdx
- src/docs/patterns/overlay.mdx
- src/docs/patterns/steppers.mdx
Fixes PXBLUE 1476.
- Update angular design pattern links to point to monorepo
> Update angular design pattern links to point to monorepo

- src/docs/development/frameworks-web/angular.mdx
- Update angular theme integration instructions to apply theme to body instead of app-root
> Apply theme to body

- src/app/components/InfoCard.tsx
- src/app/components/icons/IconCard.tsx
- src/app/components/icons/IconMenu.tsx
- src/app/components/layout/Section.tsx
- src/app/pages/LandingPage.tsx
- src/app/pages/ReleaseNotes.tsx
- src/app/pages/Roadmap.tsx
- src/app/router/navigationDrawer.tsx
- Use `theme.palette` as much as possible
> Use theme colors everywhere

- src/app/components/icons/IconMenu.tsx
> Fix links in icon menu

- src/docs/development/testing.mdx
A little wordsmithing and moving of some things around.
I left a couple TODOs in there that you can probably fill out better than I can.
> Wordsmith testing doc

- scripts/crawl/sitemap.json
- src/__configuration__/navigationMenu/navigation.tsx
- Publish /style/illustrations
> Publish the illustration guideline

- src/docs/design/websites.mdx
- remove reference to web template link on Figma
-  story added to BL - PXBLUE-1574
-
> remove TODO section for web templates to figma

- src/docs/design/accessibility.mdx
- add link icon for external resource links
- 
-
> update material design to use link icon

- src/__types__/index.ts
- src/app/api/index.tsx
- src/app/pages/Roadmap.tsx
- Add R18 roadmap (aggregate roadmap data)
- Filter by releases, not quarters
- Default roadmap results to current quarter (R18)
> Update roadmap for r18

- src/app/components/icons/IconBrowser.tsx
- src/app/components/icons/IconCard.tsx
- src/app/components/icons/IconMenu.tsx
- src/app/components/layout/ExpansionHeader.tsx
- src/app/pages/Resources.tsx
- src/app/pages/Roadmap.tsx
Fixes #276
Use `clsx` because I saw this in the source code:
> Use clsx; fix double selection error

- package.json
- yarn.lock
- added yarn-audit-fix package to dev dependencies
- https://www.npmjs.com/package/yarn-audit-fix
- usage - yarn-audit-fix
> update for security issues

- src/__configuration__/themes/diwali.ts
Fixes banner size issue
- 
- 
-
> Fix banner size

- package.json
- yarn.lock
- add source map explorer package
- Steps > yarn build > yarn analyze
> add source map for bundle size

- src/docs/design/anatomy.mdx
Fixes missing import for regular width
- 
- 
-
> add missing regularwidth import

- src/__configuration__/navigationMenu/navigation.tsx
- src/app/router/index.tsx
Fixes #257
- Add page redirect logic
- Add a page redirect from `/patterns/login` to `/patterns/user-auth`
To test: http://localhost:3000/patterns/login
> Add page redirects

- src/docs/design/intro.mdx
- src/docs/release-notes/R17/R17.mdx
- src/docs/release-notes/R18/R18.mdx
- Include a link to the design pattern stickersheet
> Update Figma links and wording

- src/app/pages/SearchBar.tsx
- src/app/router/index.tsx
> Global Search deleting characters will still search

- src/app/components/layout/PageContent.tsx
- src/app/pages/Resources.tsx
- src/app/pages/Roadmap.tsx
- Fix content overflow on Release Notes page for small screens
> Add width 100% to within PageContent

- src/docs/style/illustrations.mdx
fix slow response issue for CI build on icons8 illustrations
- 
- 
-
> change icons8 link to root

- src/app/components/icons/IconBrowser.tsx
- Fixes deep linking not working for icons.  
https://pxblue-docit.web.app/style/iconography?icon=AccessibilityNew&isMaterial=true
> Set selected icon based on query param

- src/app/components/icons/IconBrowser.tsx
Fixes https://github.com/pxblue/doc-it/pull/353#issuecomment-776955234
To verify: 
* http://localhost:3000/style/iconography?icon=AccessibleForward
* http://localhost:3000/style/iconography?icon=Apple
> Make isMaterial optional again

- src/__configuration__/themes/spring-festival.ts
> Move input color rules to colorSecondary

- package.json
- src/app/pages/SearchBar.tsx
- src/app/router/navigationDrawer.tsx
- yarn.lock
- Update to using React component library 5.0.0
- I tried to do some InfoListItem props tricks to have nav items rendered as `Link`, but that causes some issues with parent items with a landing page (clicking on only the chevron icon will also cause the browser to open a new page)
> Update to using React Component Library 5.0.0

- package.json
- src/__configuration__/themes/spring-festival.ts
- src/app/components/icons/IconBrowser.tsx
- src/app/pages/SearchBar.tsx
- src/app/router/navigationDrawer.tsx
- yarn.lock
- Fix white text on white background in search bar CNY theme
- Update to latest component library
> Deploy search bar color fix and component library update

- src/docs/style/typography.mdx
- Remove a dead link since it is already mentioned in the CTA card.
> Remove dead link about Material Design typography

- src/docs/development/cli.mdx
- add additional info with links to cli template read me
- 
-
> update to include template information

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- src/app/api/index.tsx
- src/app/pages/Roadmap.tsx
For PXBLUE-1905
- Pull a new roadmap file each time user changes the dropdown
- Remove the 'All' option
- Add options for R21
> Update logic for pulling down roadmap file

- package.json
- src/app/components/layout/CardCarousel.tsx
- yarn.lock
- Reverts to the previous implementation of the carousel
- Let's get rid of this thing next release
> Revert to 1.x of brainhubeu carousel

- src/docs/release-notes/R19/R19.mdx
Add blurp about system font size
> Add blurp about system font size

- src/__configuration__/roadmap/index.ts
- Update the default release on the roadmap to R20
- Enable R20 and R21 dropdown options
Will need a master PR after this to deploy the update.
> Update default release to R20

- src/app/pages/SearchBar.tsx
- update to include search parameters on page views to report site searches to google analytics
- 
-
> include page url search on page views

- package.json
- yarn.lock
- Bump RCL version to the latest 5.1.1 so that it shows up correctly on Safari
> Bump up RCL version to 5.1.1

- src/__configuration__/community/index.tsx
Fixes #393.
- Fix community icon vertical alignment
> Fix community icon vertical alignment

- src/app/components/layout/LinkGrid.tsx
Oopsie :P
- Those external Figma links didn't work bc I was using history API. Fixed with a link check logic.
> Fix grid cards with external links

- src/__configuration__/roadmap/index.ts
- src/docs/release-notes/R20/R20.mdx
- src/docs/release-notes/R20/Summary.mdx
- src/docs/release-notes/index.tsx
Some very basic bullet points, waiting to be changed when this sprint is over.
> Scaffold for R20 release

- src/app/components/icons/IconDrawer.tsx
Fixes https://github.com/pxblue/doc-it/issues/429 .
- Docit's icon download inspector  remember their last download option when switching from downloading material icons to pxb icons.
- 
- 
-
> keep common selected size and color of icon

- package.json
- yarn.lock
Add canvas devDependency to get tests passing
> Add canvas as devDependency

- src/__configuration__/roadmap/index.ts
- Update default release to R21 for the roadmap
> Update default release to R21

- src/__configuration__/themes/christmas.ts
- src/__configuration__/themes/diwali.ts
- src/__configuration__/themes/halloween.ts
- src/__configuration__/themes/hanukkah.ts
- src/__configuration__/themes/schedule.ts
- src/__configuration__/themes/spring-festival.ts
- src/__configuration__/themes/thanksgiving.ts
- Update holiday theme dates for 2021
> Update holiday theme dates for 2021

- scripts/crawl/sitemap.json
- src/__configuration__/navigationMenu/navigation.tsx
- src/docs/index.tsx
- src/docs/workflows/device-commissioning.mdx
- src/docs/workflows/index.tsx
This will be a hidden page on docit. No images are added. You guys can take a first pass before I turn it over to Studio Blue.
- After yarn start, go to http://localhost:3000/workflows/device-commissioning
> Add write ups about device commissioning

- src/docs/design/accessibility.mdx
- src/docs/workflows/device-commissioning.mdx
I don't think Ian will do the homework at this time... nudged him twice but I guess he's busy with his fatherhood
- Added feedback from Eric and Mike
- Grammarly'd the grammar
> Apply Feedbacks from Studio Blue

- src/app/pages/SearchBar.tsx
Fixes #193
- Dismiss mobile keyboard on search
https://user-images.githubusercontent.com/8997218/146436631-07716848-6b18-49e0-acf3-a9892fe7356f.mov
> Dismiss mobile keyboard on search

- src/app/components/contributors/ContributorsCard.tsx
- src/app/components/docsUtil/ImageGrid.tsx
- src/app/router/navigationDrawer.tsx
> Update to vent deprecation warning

- src/__configuration__/navigationMenu/navigation.tsx
- src/docs/community/index.tsx
- src/docs/community/migration.mdx
- src/docs/community/rebrand.mdx
Fixes 2632 .
- Add package migration details 
- http://localhost:3000/brightlayer-ui-package-migration
> add migration notice

- src/docs/patterns/steppers.mdx
Talk about RN mobile stepper in docs
> Advertise mobile stepper in the docs

- src/docs/patterns/loading.mdx
> Update to point to the latest Skeleton API

- src/__configuration__/navigationMenu/navigation.tsx
> Go BLUI, but shorter

- src/docs/release-notes/R22/R22.mdx
- src/docs/release-notes/R22/Summary.mdx
> Add a few suggestions for release notes

- package.json
- src/docs/release-notes/R22/R22.mdx
Fixes # .
- update with design pattern example
- 
- 
-
> and pattern examples & links to R22 notes

- src/docs/community/license.mdx
- Fix deadlink
Brightlayer UI is open source and licensed under the [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause) license agreement.
> Fix dead link

- src/app/components/typography/TypographyTable.tsx
> Remove one column

- src/app/components/typography/TypographyTable.tsx
> Remove that space in the headline typography entries

- src/app/redux/reducers/index.ts
- Turn off the announcement banner for Q2; ppl should be aware by now that we are renamed as Brightlayer UI
> Turn off announcement banner for Q2

- src/docs/community/bugs.mdx
- src/docs/community/features.mdx
- src/docs/development/frameworks-web/react.mdx
- src/docs/patterns/forms.mdx
- src/docs/patterns/internationalization.mdx
- src/docs/release-notes/R10/FullNotes.mdx
- src/docs/release-notes/R23/FullNotes.mdx
- src/docs/release-notes/R23/Summary.mdx
- src/docs/style/themes.mdx
Fixes # .
- start updating release note for dev
- update react getting started
- 
-
> Update dev release notes

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- Include R25 in the dropdown for Releases
> Include R25 as a roadmap option

- src/__configuration__/navigationMenu/navigation.tsx
> Add that plural s

- src/docs/development/components.mdx
- Add more texts to describe our components, as mentioned in the demo
> Add more texts to describe our components

- src/docs/release-notes/R25/FullNotes.mdx
Fixes BLUI-3590.
- Add React Native packages to R25 package summary
> Add React Native packages to R25 package summary

- src/__configuration__/themes/diwali.ts
> hotfix: Turn off Diwali theme

- .circleci/config.yml
> Turn off link checker in CI

- CODEOWNERS
- README.md
- src/docs/community/bugs.mdx
- src/docs/community/code-of-conduct.md
- src/docs/community/contributing-guideline.md
- src/docs/community/features.mdx
- src/docs/community/innersourcing.mdx
Just want a place to host these files, so that I can make changes to all readmes for BLUI.
> Add community guides to docit

- src/__configuration__/contributors/contributors.ts
- src/__configuration__/contributors/currentMaintainers.ts
> Update "current maintainers" list

- src/__configuration__/themes/_schedule.ts
- src/__configuration__/themes/diwali.ts
- src/__configuration__/themes/hanukkah.ts
- src/__configuration__/themes/mid-autumn-festival.ts
Fixes BLUI-3624.
- Update the holiday schedule
> Update the holiday schedule

- src/docs/release-notes/R22/FullNotes.mdx
- src/docs/release-notes/R23/FullNotes.mdx
- src/docs/release-notes/R25/FullNotes.mdx
- Fix those broken changelog links caused by yarn workspace master merge
> Fix icon repos' changelog links

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
Please also help review https://github.com/etn-ccis/blui-database/pull/35
> Update roadmap to R27

- src/docs/release-notes/R26/Summary.mdx
- yarn.lock
Fixes [#650](https://github.com/etn-ccis/blui-doc-it/issues/650)
- removed the unwanted semicolons in the Latest Updates text
> semicolons removed

- src/app/components/contributors/MaintainersCards.tsx
Fixes #676 
- Updated the mobile view so that the Our Team cards are 1 column to fix the "squeeze" issue
- 
-
-
> Updated mobile view for Our Team cards to 1 column

- src/app/components/icons/DeveloperInstructions.tsx
Fixes #647
- Updated arrangement of Icon Components within accordion 
- Changed text to say "Icon Components (Recommended)"
- 
-
-
> Updated icon component arrangement and text

- package.json
- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- src/docs/release-notes/R28/FullNotes.mdx
- src/docs/release-notes/R28/Summary.mdx
- src/docs/release-notes/index.tsx
- yarn.lock
Fixes 4441 .
- R28 Release Update
-
-
-
-
- Design sides updates are remaining
> Developer Resources Release Note

- src/__configuration__/resources/index.tsx
Fixes # BLUI-4953
- Removed branding package from developer resources
- yarn start
- Navigate to Resources -> Developer Resources
-
> Removed colors branding package from developer resources

- .github/workflows/firebase-hosting-pull-request.yml
> TEST DO NOT MERGE

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
Fixes #BLUI-5150.
- Added R31 roadmap 
-
-
-
> R30 Release Announcement

- src/docs/style/color.mdx
Fixes #BLUI-5762 .
- Updated colors palette documentaion.
-
-
-
> Clean up colors documentation to be more clear about MD2/MD3

- src/__configuration__/contributors/contributors.ts
- src/__configuration__/contributors/currentMaintainers.ts
- Updated main page by moving profile from other contributors to current maintainers.
- Added profile onto 'Our Team' page
- 
-
> Updating my info for current maintainers and adding to Our Team page

- src/docs/release-notes/R32/FullNotes.mdx
Fixes # .
- update the packages version
-
-
-
-
-
> updated package version for release

- src/docs/development/frameworks-web/react.mdx
- Fix react ui themes typo
- Navigate to https://brightlayer-ui.github.io/development/frameworks-web/react#applying-the-theme
- Ensure typo is fixed
> Fix react ui themes typo

- .github/workflows/blui-ci.yml
Fixes # .
- revert changes from dependabot update
-
-
-
-
> revert to version 3 actions/download-artifact

- src/docs/development/frameworks-mobile/react-native.mdx
- src/docs/development/frameworks-web/angular.mdx
- src/docs/development/frameworks-web/react.mdx
- src/docs/development/templates.mdx
- src/docs/get-started/new-project.mdx
Fixes # .
Review comments from https://github.com/etn-ccis/blui-doc-it/pull/780 PR is addressed 
- Removed blui cli references
-
-
-
> Review changes - Removed blui cli references

- CODEOWNERS
- package.json
- yarn.lock
> Updated CODEOWNERS

- .github/workflows/blui-ci.yml
- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- src/docs/release-notes/R32/FullNotes.mdx
- src/docs/release-notes/R33/FullNotes.mdx
- src/docs/release-notes/R34/FullNotes.mdx
- src/docs/release-notes/R34/Summary.mdx
- src/docs/release-notes/index.tsx
> Added release note for R34

- src/docs/style/icon-guidelines.mdx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/573.
- update No Single-Purpose Icons anchor link
- remove link check disable
-
- anchor link
https://blui-doc-it--pr797-bug-update-same-page-bixxzj9h.web.app/style/icon-guidelines#no-single-purpose-icons
or
- select no single purpose icons link from this section
https://blui-doc-it--pr797-bug-update-same-page-bixxzj9h.web.app/style/icon-guidelines#common-device-icons
-
-
> update anchor link

- src/docs/visualizations/piecharts.mdx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/790.
- update space in Pie Charts
-
-
-before
-after
https://blui-doc-it--pr798-bug-fix-headline-spa-w6bilq6o.web.app/visualizations/piecharts
-
-
> fix pie charts headline spacing

- src/__configuration__/landingPage/externalLinks.ts
Fixes https://github.com/etn-ccis/blui-doc-it/issues/740.
- update studio blue link
-
-
-
-
-
> update studio blue link related sites

- src/docs/release-notes/R12/FullNotes.mdx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/698.
- fix release link june 2019 section
-
-
-
-
> fix link in release notes june 2019 section

- src/docs/visualizations/barcharts.mdx
- src/docs/visualizations/linecharts.mdx
- src/docs/visualizations/piecharts.mdx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/789.
- update bar charts  sub-title size to match other screens
-
-
-
-
> update barchart headline to match other screens

- __scripts__/crawl/sitemap.json
- src/__configuration__/landingPage/externalLinks.ts
- src/__configuration__/navigationMenu/navigation.tsx
- src/docs/resources/community.mdx
- src/docs/resources/index.ts
> Add Community Docs link to doc-it

- src/docs/development/frameworks-mobile/react-native.mdx
Fixes #BLUI-6460 .
-
-
-
-
-
-
> Reverted urls to master branch

- src/docs/patterns/user-auth.mdx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/739.
- update missing link for angular login workflow
-
-
-
- go to https://blui-doc-it--pr810-bug-fix-ng-login-lin-5n27gb6j.web.app/patterns/user-auth
- click on Angular link
-
> Fix link for NG login workflow example

- src/__configuration__/navigationMenu/navigation.tsx
- src/app/router/index.tsx
Fixes https://github.com/etn-ccis/blui-doc-it/issues/572.
- remove redirect logic
-
-
-
- any old bookmarks/links that are unknown will route to root path '/'
- https://blui-doc-it--pr811-bug-remove-redirect-0f1i1dmf.web.app/about
-
> Remove redirect logic

- src/__configuration__/community/BluiProjects.ts
Fixes https://github.com/etn-ccis/blui-doc-it/issues/692.
- update product names for apps using blui
-
-
-
- https://blui-doc-it--pr813-feature-product-name-lq086mt0.web.app/community/blui-projects
-
> Update product names apps using BLUI

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- src/docs/release-notes/R35/FullNotes.mdx
- src/docs/release-notes/R35/Summary.mdx
- src/docs/release-notes/index.tsx
> updated doc it for release Q1 2025

- src/docs/release-notes/R35/FullNotes.mdx
- src/docs/release-notes/R35/Summary.mdx
> Q1 release 2025 update

- src/docs/release-notes/index.tsx
> updated release notes month for Q1

- src/__configuration__/roadmap/index.ts
- src/__types__/index.ts
- src/docs/release-notes/R35/FullNotes.mdx
- src/docs/release-notes/R36/FullNotes.mdx
- src/docs/release-notes/R36/Summary.mdx
- src/docs/release-notes/index.tsx
Fixes #6803 .
- Added the summary, Release Notes and Roadmap for R36 release.
- 
-
> R36 Release updates

- src/app/shared/constants.ts
Fixes # BLUI-6874 #684
- Updated max width for markdown content
- 
- yarn start
- Navigate to Style Guide -> Typography
-
> Updated max width of markdown content

- src/app/components/colors/ColorBottomSheet.tsx
- src/app/components/colors/Colors.tsx
Fixes # . BLUI-6898
#842 
- Fixed colour palette issue
-
-
-
-
-
> Fixed color palette issue

- src/app/components/colors/ColorBottomSheet.tsx
Fixes # . BLUI-6898
- Fixed Color Palette issue on Page Reload
-
-
-
-
-
> Fixed Color Palette issue on Page Reload

- src/__configuration__/contributors/contributors.ts
- src/__configuration__/contributors/currentMaintainers.ts
Fixes  https://github.com/etn-ccis/blui-doc-it/issues/844 .
- updated current maintainers list and our team section.
-
-
- 
-  check in other contributors section Ekta and jeff info should be there
-  Go to our Team section in community both name should not be there.
-
> updated current maintainers list and our team section
