etn-ccis/blui-doc-it

package.json
src/app/assets/icons/index.tsx
src/app/assets/icons/materialDesign.tsx
src/app/components/colors/Colors.tsx
src/app/components/icons/ProgressIconCard.tsx
src/app/components/navigation/SharedToolbar.tsx
src/app/components/patterns/MaterialDesignDescription.tsx
src/app/components/patterns/index.tsx
src/app/pages/Roadmap.tsx
src/app/router/navigationDrawer.tsx
src/docs/patterns/appbar.mdx
src/docs/patterns/empty-states.mdx
src/docs/patterns/forms.mdx
src/docs/patterns/internationalization.mdx
src/docs/patterns/layout.mdx
src/docs/patterns/lists.mdx
src/docs/patterns/navigation.mdx
src/docs/patterns/overlay.mdx
src/docs/patterns/visualizations.mdx
src/docs/style/color.mdx
src/docs/style/iconography.mdx
src/docs/style/themes.mdx
src/docs/style/typography.mdx
yarn.lock

- Added component `MaterialDesignDescription`
- Add the corresponding material io link to the design pattern pages and style guide pages
- Prettier.

Add material design description card

---

src/app/components/icons/IconBrowser.tsx
src/app/components/icons/IconCard.tsx
src/app/components/icons/IconMenu.tsx
src/app/hooks/useQueryString.tsx
src/app/shared/utilities.tsx

Fixes #150.
Fixes #159. 
- Fix the overflow on the icon bottom sheet
- Use query string to deep link to icons
- Update the address bar when user selects an icon
- Automatically expand the appropriate group if the user deep links to an icon
- Add React Native instructions to bottom sheet
- Fix some minor bugs
You can deep link to icons by going to:
https://pxblue.github.io/style/iconography?icon=IconName
You can prepopulate the search field by going to:
https://pxblue.github.io/style/iconography?search=Search%20Query

Ability to deep link to icons

---

src/__types__/index.ts
src/app/pages/Roadmap.tsx

- Add another roadmap status for "pre-release"
- Shows a purple ListItemTag
- Add another roadmap status for 'deferred'
- Shows an orange ListItemTag

Add prerelease and deferred tags for roadmap

---

src/docs/patterns/forms.mdx

Fixes #197.
Prettier converted a lone asterisk to underscore a while back. This switches it back and escapes it
- Switch asterisk back to asterisk
- Escape the asterisk

Escape asterisk character

---

src/app/components/icons/IconBrowser.tsx
src/app/hooks/usePrevious.tsx
src/app/pages/SearchBar.tsx

Fixes #190.
- Parse URL to deep link into search `.....?search=<searchquery>`
- Handle loading results based strictly on the URL
- Ability to go forward and back (browser) through search results correctly

Add ability to deep link to search results

---

src/app/components/icons/IconBrowser.tsx
src/app/components/icons/ProgressIconCard.tsx

- Added a little switch in the progress icon card to view the outlined icons

Show outlined progress icons

---

src/__configuration__/markdown/markdownMapping.tsx

- Move the deep link anchor point
- 
- 
Before: deeplink scrolls the webpage to a position covered by app bar
Now: A -90 buffer would space things properly

Move the deeplink anchor up

---

src/app/components/icons/IconBrowser.tsx
src/app/components/icons/IconGrid.tsx

- Don't run the icon loading logic when loading the landing page
- Load the icons after the first render of the iconography page
- Convert the metadata arrays into objects for faster search/indexing

Optimize the icon loading logic for faster rendering

---

src/__configuration__/contributors/contributors.ts
src/__configuration__/contributors/currentMaintainers.ts

- Switch Kyle from maintainer to contributor

Update Kyle's role

---

src/app/pages/Resources.tsx

Fixes #316 
- Adds style to prevent resource page from having dynamic width for each framework tab.
Hosted here: https://pxblue-docit.web.app/resources

Fix width changing per framework on resource page

---

src/app/pages/SearchBar.tsx

Fixes the thing we talked about in the chat
- Replace the look ahead syntax with some string slicing logic
To test, open up localhost in Safari.

Fix the query regex problem causing safari trouble

---

src/app/router/navigationDrawer.tsx
yarn.lock

I find the square activeBackgroundShape really awkward when nested items are involved — can be hard to see which one is getting selected. 
- useCallback to calculate the background color
- changed `activeItemBackgroundShape` to `round`
I have another branch `feature/condensed-drawer` that plays around with the condensed drawer item variant, according to an earlier proposed drawer design. I know the design is not "final-final" yet, but as more and more pages are getting added to docit, I think it's time for docit to have a condensed drawer.

Make the item round again

---

src/__configuration__/markdown/markdown.css
src/__configuration__/markdown/markdownMapping.tsx
src/app/components/colors/Colors.tsx

I found myself keep copying & pasting hex code and it annoys me that I cannot do that in one click.
- Add a copy-on-click functionality
- Shrink the hover area of those headlines, so that there would be no more unexpected misclicks.
This works for both hex and rgb.
| default | hover | clicked | your clipboard now is
| - | - | - | - |
| ![image](https://user-images.githubusercontent.com/8997218/116143146-c41ec700-a6a8-11eb-990e-0b7dfae854bc.png) | ![image](https://user-images.githubusercontent.com/8997218/116143159-c97c1180-a6a8-11eb-85ef-1d06190bf009.png) | ![image](https://user-images.githubusercontent.com/8997218/116143178-ced95c00-a6a8-11eb-92b8-725e901794f2.png) |`#004b9e`
| ![image](https://user-images.githubusercontent.com/8997218/116143465-2ed00280-a6a9-11eb-9307-cfc50fb95a73.png) …

Add copy on click functionality

---

package.json

Fixes #424 
- Move yarn indexer out of precommit and move into yarn build
- This means that we always have an outdated local global search (unless someone triggers it manually). Do we want this?

Move indexer to yarn indexer script

---

src/app/components/icons/IconBrowser.tsx
src/app/components/icons/IconDrawer.tsx
src/app/components/icons/IconGrid.tsx
src/app/components/icons/utilityFunctions.tsx
src/app/shared/utilities.tsx

Fixes #486
- Fixed EV Plug code snippet
- Ensure that EV Plug icons SVG and PNGs can both download properly
- Fixed a few places that still has traces of pxblue
- Verify that the four EV plugs mentioned in the bug report now have correct usage instructions
- Verify that the copy button for those code snippets copy correctly
- Verify that the Icon Drawer display the icon title correctly
- Verify that everything downloads and opens correctly. (Icons with wrong names can still be downloaded, but the file is corrupted and won't open)
- Verify that other regular icons (both blui icons and Material icons) are left untouched

Ensure EV Plug instructions and links all works

---

src/__configuration__/roadmap/index.ts
src/__types__/index.ts

So that docit displays the roadmap in https://github.com/brightlayer-ui/blui-database/pull/6

Bump CURRENT_RELEASE to R23

---

src/app/pages/SearchBar.tsx
src/index.css

- Remove the browser default "X" from the search field
- Just a small thing but it bugs me a little...
- 
Before: 
https://user-images.githubusercontent.com/8997218/149817595-4a767e15-435e-460e-9740-7273a22166b2.mov
After:
https://user-images.githubusercontent.com/8997218/149817606-a3455546-f466-417b-87ae-28462bd9286b.mov
- search for something
- hover your mouse in the search field
- ensure that the x does not appear

Remove "X" from the search field

---

src/__configuration__/navigationMenu/navigation.tsx

There's an extra slash in the "App Logo" page's URL

Remove extra slash

---

src/__types__/index.ts
src/app/api/index.tsx
src/app/components/icons/IconBrowser.tsx
src/app/components/icons/index.tsx
src/app/components/icons/utilityFunctions.tsx
src/app/shared/utilities.tsx

Fixes #590.
- Dynamically create download links using version from material metadata
- Fix issue with filename converter utilities when there are numbers in the name
- Attempt to download the `Notifications` icon and the `Battery-0-Bar` icons
- these are from two different versions of icons and previously could not both be downloaded successfully

Use dynamic version to create icon download links

---

src/docs/release-notes/R27/FullNotes.mdx
src/docs/release-notes/R27/Summary.mdx
src/docs/release-notes/index.tsx

Fixes BLUI-3923
- Added release notes for R27
- Looking mostly for feedback on wording and whether I covered all "announceable" efforts. 
- Note that not everything works 100% in this PR due to several pending efforts:
- Roadmap is still pointing to R27, because there is no R28 in the blui-database. I assume this will be updated after the PI planning
- None of the React dev doc links work, because it has not been merged to master yet
- angular and react component libraries are still waiting for their master PR to be actually published.

Added release notes for R27

---

src/app/shared/utilities.tsx

Fixes #482 
- document.execCommand('copy') is deprecated so replaced it with Clipboard API to resolve
-
-
-

Replaced execCommand with the Clipboard API

---

CODEOWNERS
src/__configuration__/design/resources.tsx

- Added a link to the new Material Design 3 component sticker sheet
- Codeowner, replace Tom with Suraj
- yarn start
- http://localhost:3000/resources/designer

Add MD3 component stickersheet to design resources

---

.circleci/config.yml
.github/workflows/firebase-hosting-pull-request.yml
src/__configuration__/themes/_schedule.ts
src/__configuration__/themes/christmas.ts
src/__configuration__/themes/diwali.ts
src/__configuration__/themes/halloween.ts
src/__configuration__/themes/hanukkah.ts
src/__configuration__/themes/independence-day.ts
src/__configuration__/themes/kwanzaa.ts
src/__configuration__/themes/mid-autumn-festival.ts
src/__configuration__/themes/spring-festival.ts
src/__configuration__/themes/thanksgiving.ts

Fixes BLUI-5024
- Update dates for holiday themes
- Update docker images

Update docit holiday schedule for 2024

---

.circleci/config.yml
package.json
yarn.lock

Fixes BLUI-4717
Get the new icons published [here](https://github.com/etn-ccis/blui-icons/pull/307) to show on docit
- Verify that all the new icons are showing properly on the icons page http://localhost:3000/style/icon-library
- I need help with the CI error on Chrome Driver

BLUI-4717: Use the latest icon package for the new icons

---

src/__configuration__/navigationMenu/navigation.tsx

Fixes https://github.com/etn-ccis/blui-doc-it/issues/406
- move web & mobile intro page to root parent nav
-
-
- before
- after
-
-

Move web & mobile intro pages to parent nav item

---

src/__configuration__/contributors/currentMaintainers.ts
src/docs/development/frameworks-mobile/react-native.mdx

Fixes https://github.com/etn-ccis/blui-doc-it/issues/807 .
- Updated github urls for fonts and license info in React Native Guide page
-
-
-
-
-

updated url for react native theme and license info
